### PR TITLE
[security] protect against Man in the Middle attacks when minifying draggable.js

### PR DESCRIPTION
**Pull request by dotnetCarpenter**
This PR is a patch but is an important one. When minifying, we make a request to closure-compiler.appspot.com and trust that their return string is not an evil version of draggable.js. This assumption could be wrong as an attacker could intercept our call and return his evil code, which we will distribute to draggable.js users, who will embed it in their website. Hence the attacker will gain control of these websites.

### CODE REVIEW

**Comment by dotnetCarpenter** [comment]
@gtramontina @bung87 thoughts?

**Comment by gtramontina** [comment]
:+1: I'd even have everything local, with `uglifyjs` or something like that... I don't really remember the reason why I chose using that service. :stuck_out_tongue:

**Comment by dotnetCarpenter** [comment]
One thing I really like about using closure-compiler is how easy it is to get es6 support. Doing it locally is lot of boilerplate code to get it in a shape for es5.1 browsers. Plus it creates two main files. One for es5 and one for es6, unless you don't expose es6. [rollup](https://github.com/rollup/rollup) has suggested the [`jsnext:main`](https://github.com/rollup/rollup/wiki/jsnext:main) property to package.json. But everything still seems in beta state across all module loaders, package builders and transpilers when it comes to es6. Lot of solutions, none of them coherent.

Arhh, the same argument could possibly be applied to closure-compiler, but at least you didn't setup anything, that needs to change soon.

**Comment by bung87** [comment]
@dotnetCarpenter for security season,I think this is a good work,although I often use  grunt uglifyjs to do minifying.

**Comment by dotnetCarpenter** [comment]
Right.. I'll make this PR more edible -  figuratively speaking.

**Comment by dotnetCarpenter** [comment]
Right.

### Usage:
Just do `make` and make will see if `draggable.min.js` and `draggable.min.js.map` exist and are newer than `draggable.js`. If any of these conditions are false, make will call uglifyjs directly with `draggable.js`.

**Pull request merged**
