### PR TITLE
make it works fine with absolute position element

### PR DESCRIPTION
**Pull request by bung87**

### CODE REVIEW

**Comment by bryangoldberg** [comment]
This works pretty exceptionally. Thank you! Literally the only plugin that has worked with my input boxes. When dragging on a scaled div in big strokes or on larger div's, the mouse seems to not be positioned on the dragged element anymore. Hence, directing the dragged element with an offset mouse rather than dragging your element with your mouse.

Anyway you could take a look and check this out?

Here is my jsfiddle: http://jsfiddle.net/Lzn4vLeq/2/

**Comment by bung87** [comment]
seems like face the same problems on stackoverflow , here is the link http://stackoverflow.com/questions/6773481/how-to-get-the-mouseevent-coordinates-for-an-element-that-has-css3-transform ,maybe you could create a PR to fix this.thank you for have me known about this.

**Comment by bryangoldberg** [comment]
I'd love to. However I tried and it's a bit over my head. I'm not nearly knowledgable enough.

**Comment by AkeemMcLennon** [comment]
@gtramontina Any plans to merge this into master?

**Comment by gtramontina** [comment]
Holy smokes! I'm really sorry, everyone. This have totally slipped through my fingers! Merging it! :beers: Thanks for the PR, @bung87 ... thanks for poking me, @AkeemMcLennon :smile:

**Comment by gtramontina** [comment]
... and released https://github.com/gtramontina/draggable.js/releases/tag/v1.0.1 -- should also be available on bower.

**Pull request merged**
